import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import bgPic from "assets/bw-transparent.png";
import { Parallax, ParallaxProvider } from "react-scroll-parallax";
import { useEffect, useState } from "react";
import Hero from "components/home/Hero";

const Home: NextPage = () => {
  const [innerHeight, setInnerHeight] = useState(0);

  useEffect(() => {
    if (window) {
      setInnerHeight(window.innerHeight)
    }
  }, []);

  return (
		<ParallaxProvider>
			<Head>
				<title>Naufal Mukhbit&apos;s Website</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<article className="text-center">
        <Parallax
          speed={-50}
          startScroll={innerHeight * -1}
          endScroll={innerHeight}
        >
          <Hero />
        </Parallax>
        <Parallax>
          <div className="bg-white text-black h-[200vh]">
            Test
          </div>
        </Parallax>
			</article>
		</ParallaxProvider>
	);
};

export default Home;
