import { useState, useCallback, useEffect, useRef } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "components/common";
import { FakeWindow, HomeFooter, Projects, BlogPosts } from "components";

const Home: NextPage = () => {
  const [scrollY, setScrollY] = useState(0);
  const [innerHeight, setInnerHeight] = useState(0);

  const aboutRef = useRef(null);
  const blogRef = useRef<HTMLDivElement>(null);
  const projectRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (window) {
      setInnerHeight(window.innerHeight);
    }
  }, []);

  const handleNavigation = useCallback((e) => {
    const window = e.currentTarget;
    setScrollY(window.scrollY);
  }, []);

  useEffect(() => {
    setScrollY(window.scrollY);
    window.addEventListener("scroll", handleNavigation);

    return () => {
      window.removeEventListener("scroll", handleNavigation);
    };
  }, [handleNavigation]);

  const toAbout = () => window.scrollTo({ top: 1300, left: 0, behavior: "smooth" });

  const toBlog = () => blogRef.current?.scrollIntoView({ behavior: "smooth" });

  const toProject = () => projectRef.current?.scrollIntoView({ behavior: "smooth" });

  return (
    <div className="flex flex-col">
      <Head>
        <title>Naufal Mukhbit&apos;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        scroll={scrollY}
        toAbout={toAbout}
        toBlog={toBlog}
        toProject={toProject}
      />
      <div
        className="relative bg-yellow-50 dark:bg-slate-500 transition"
        style={{ height: 1500 + innerHeight }}
      >
        <FakeWindow scroll={scrollY} />
      </div>
      <div className="relative">
        <div className="absolute top-0">
          <div id="blog" ref={blogRef}>
            <BlogPosts />
          </div>
          <div id="project" ref={projectRef}>
            <Projects />
          </div>
          <div className="py-20 flex justify-center">
            <div className="flex flex-row-reverse justify-center items-center text-4xl font-bold text-black/10 dark:text-white/5">
              More things coming soon 👀
            </div>
          </div>
          <HomeFooter />
        </div>
      </div>
    </div>
  );
};

export default Home;
